void place_string(int side, int line, double size, char *st);
void place_multistate(int side, int line, char *Opt1, char *Opt2, char *Opt3, char *active);
int process_scratchpad(char *st, char *var);
char *get_data(void);
int DecToDMS(double decimal, char *DMS, int which);
void JulianToDayMonth(int julian, int *day, int *month);
int ReadAircraftCFG(void);
void LoadNavData(void);
void mouse2(int x, int y);
void mouse(int button, int state, int x, int y);

void draw_cdu_ident(void);
void draw_cdu_index(void);
void draw_maint(void);
void draw_pos_ref(void);
void draw_dashed_line(double left, double right, int line);
void draw_perf_init(void);
void draw_route(int route);
void draw_route_legs(int route);
void draw_menu(void);
void draw_efis(void);
void draw_efis_options(void);
void draw_display_mode(void);
void draw_display_synoptics(void);
void draw_fmc_comm(void);
void draw_dep_arr(void);
int	SetPage(void);
int GetTime(void);
double bcdToFreq(int bcd);
int navrad_preval(void);
int vor_lVal(void);
int vor_rVal(void);
long find_object(char *name);
int crs_lVal(void);
int crs_rVal(void);
int SetModel(void);
int OpenDatabase(void);
int CloseDatabase(void);
int PreSelect_l(void);
int PreSelect_r(void);
int SetSpeeds(void);
int PrepEFIS(void);
int PrepDSP(void);
int ToggleEFIS(void);
int ToggleDSP(void);
int CheckEFIS(void);
int CheckDSP(void);
int PrepADFVOR(void);
int SetADFVOR(void);
int SetDSPMode(void);
int ChkDSPMode(void);
int SetSYNMode(void);
int ChkSYNMode(void);
int SetEFISMode(void);
int ChkEFISMode(void);
int DecrRange(void);
int IncrRange(void);
int SetEFISOpt(void);
int ChkPosPage(void);
int GetAirport(void);
int GetOrigin(void);
int GetDestination(void);
int PrepDepArr(void);
int ValidateRunway(void);
int SelectProc(void);
int SelectRunway(void);

// Database Stuff<tm>
int DBValidateRunway(char *name);
int DBGetDepartures (char *name);
int DBGetArrivals (char *name);
int DBGetNavaids (char *);
int DBGetAirport (char *);
int DBGetOriginAirport(char *);
int DBGetDestinationAirport(char *);
int GetTransitions(void);
